version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - redis

  telegram:
    build:
      context: .
      dockerfile: telegram/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
      dockerfile: library/Dockerfile
    command: celery -A your_django_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - library
