# Generated by Django 5.1.2 on 2024-10-19 13:35

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=books.models.book_image_path
            ),
        ),
    ]
