# Generated by Django 5.1.2 on 2024-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_daily_fee_alter_book_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.CharField(max_length=128),
        ),
    ]
