# Generated by Django 5.1.2 on 2024-11-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["id"], "verbose_name": "Borrowing"},
        ),
    ]
