# Generated by Django 5.1.2 on 2024-10-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow_payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=252),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=500),
        ),
    ]
