# Generated by Django 5.1.2 on 2024-10-18 12:49

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(null=True, upload_to=books.models.book_image_path),
        ),
    ]
